### ISSUE TITLE
javascript PoC validation

### ISSUE THREAD

**Issue by trillville** [getsentry/timeseries-analysis-service#106]
using sentry's javascript project, evaluate performance on JS errors. Reference notebook: https://github.com/getsentry/data-analysis/blob/main/embeddings/gpt4_label_training.ipynb

This may be complicated by the number of issues relative to the dimensionality of the embeddings - if its less than 500 or so issues we may have a problem and need to think of a simpler model.
```[tasklist]
### Tasks
- [ ] generate issues dataset from JS project
- [ ] label issues dataset (same process as notebook)
- [ ] Generate embeddings (same process as notebook)
```
